/*
* generated by Xtext
*/
package hu.bme.mit.androtext.lang.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import hu.bme.mit.androtext.lang.services.AndroTextDslGrammarAccess;

public class AndroTextDslParser extends AbstractContentAssistParser {
	
	@Inject
	private AndroTextDslGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected hu.bme.mit.androtext.lang.ui.contentassist.antlr.internal.InternalAndroTextDslParser createParser() {
		hu.bme.mit.androtext.lang.ui.contentassist.antlr.internal.InternalAndroTextDslParser result = new hu.bme.mit.androtext.lang.ui.contentassist.antlr.internal.InternalAndroTextDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelRootAccess().getAlternatives(), "rule__ModelRoot__Alternatives");
					put(grammarAccess.getAndroidApplicationModelElementAccess().getAlternatives(), "rule__AndroidApplicationModelElement__Alternatives");
					put(grammarAccess.getTypeRefAccess().getAlternatives(), "rule__TypeRef__Alternatives");
					put(grammarAccess.getUIElementAccess().getAlternatives(), "rule__UIElement__Alternatives");
					put(grammarAccess.getRootLayoutAccess().getAlternatives(), "rule__RootLayout__Alternatives");
					put(grammarAccess.getBaseLayoutAccess().getAlternatives(), "rule__BaseLayout__Alternatives");
					put(grammarAccess.getLinearLayoutAccess().getAlternatives_2(), "rule__LinearLayout__Alternatives_2");
					put(grammarAccess.getWidgetAccess().getAlternatives(), "rule__Widget__Alternatives");
					put(grammarAccess.getRadioGroupAccess().getAlternatives_2(), "rule__RadioGroup__Alternatives_2");
					put(grammarAccess.getAbstractPreferenceAccess().getAlternatives(), "rule__AbstractPreference__Alternatives");
					put(grammarAccess.getResourceAccess().getAlternatives(), "rule__Resource__Alternatives");
					put(grammarAccess.getArrayResourceAccess().getAlternatives(), "rule__ArrayResource__Alternatives");
					put(grammarAccess.getDrawableResourceAccess().getAlternatives(), "rule__DrawableResource__Alternatives");
					put(grammarAccess.getDimensionValueAccess().getAlternatives_1(), "rule__DimensionValue__Alternatives_1");
					put(grammarAccess.getBOOLAccess().getAlternatives(), "rule__BOOL__Alternatives");
					put(grammarAccess.getApiLevelAccess().getAlternatives(), "rule__ApiLevel__Alternatives");
					put(grammarAccess.getDataTypesAccess().getAlternatives(), "rule__DataTypes__Alternatives");
					put(grammarAccess.getLayoutStyleAccess().getAlternatives(), "rule__LayoutStyle__Alternatives");
					put(grammarAccess.getAndroTextModelRootAccess().getGroup(), "rule__AndroTextModelRoot__Group__0");
					put(grammarAccess.getAndroTextModelRootAccess().getGroup_0(), "rule__AndroTextModelRoot__Group_0__0");
					put(grammarAccess.getImportAccess().getGroup(), "rule__Import__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup(), "rule__QualifiedName__Group__0");
					put(grammarAccess.getQualifiedNameAccess().getGroup_1(), "rule__QualifiedName__Group_1__0");
					put(grammarAccess.getQualifiedNameWithWildCardAccess().getGroup(), "rule__QualifiedNameWithWildCard__Group__0");
					put(grammarAccess.getQualifiedNameWithWildCardAccess().getGroup_1(), "rule__QualifiedNameWithWildCard__Group_1__0");
					put(grammarAccess.getAndroGenModelRootAccess().getGroup(), "rule__AndroGenModelRoot__Group__0");
					put(grammarAccess.getTargetApplicationAccess().getGroup(), "rule__TargetApplication__Group__0");
					put(grammarAccess.getTargetApplicationAccess().getGroup_5(), "rule__TargetApplication__Group_5__0");
					put(grammarAccess.getVersionCodeAccess().getGroup(), "rule__VersionCode__Group__0");
					put(grammarAccess.getAndroidPackageNameAccess().getGroup(), "rule__AndroidPackageName__Group__0");
					put(grammarAccess.getAndroidPackageNameAccess().getGroup_1(), "rule__AndroidPackageName__Group_1__0");
					put(grammarAccess.getAndroidApplicationAccess().getGroup(), "rule__AndroidApplication__Group__0");
					put(grammarAccess.getAndroidApplicationAccess().getGroup_3(), "rule__AndroidApplication__Group_3__0");
					put(grammarAccess.getActivityAccess().getGroup(), "rule__Activity__Group__0");
					put(grammarAccess.getTabActivityAccess().getGroup(), "rule__TabActivity__Group__0");
					put(grammarAccess.getAndroDataModelRootAccess().getGroup(), "rule__AndroDataModelRoot__Group__0");
					put(grammarAccess.getEntityAccess().getGroup(), "rule__Entity__Group__0");
					put(grammarAccess.getEntityAccess().getGroup_2(), "rule__Entity__Group_2__0");
					put(grammarAccess.getPropertyAccess().getGroup(), "rule__Property__Group__0");
					put(grammarAccess.getAndroGuiModelRootAccess().getGroup(), "rule__AndroGuiModelRoot__Group__0");
					put(grammarAccess.getAbsoluteLayoutAccess().getGroup(), "rule__AbsoluteLayout__Group__0");
					put(grammarAccess.getLinearLayoutAccess().getGroup(), "rule__LinearLayout__Group__0");
					put(grammarAccess.getFrameLayoutAccess().getGroup(), "rule__FrameLayout__Group__0");
					put(grammarAccess.getRelativeLayoutAccess().getGroup(), "rule__RelativeLayout__Group__0");
					put(grammarAccess.getTextViewAccess().getGroup(), "rule__TextView__Group__0");
					put(grammarAccess.getEditTextAccess().getGroup(), "rule__EditText__Group__0");
					put(grammarAccess.getButtonAccess().getGroup(), "rule__Button__Group__0");
					put(grammarAccess.getListViewAccess().getGroup(), "rule__ListView__Group__0");
					put(grammarAccess.getListViewAccess().getGroup_4(), "rule__ListView__Group_4__0");
					put(grammarAccess.getListViewAccess().getGroup_5(), "rule__ListView__Group_5__0");
					put(grammarAccess.getSpinnerAccess().getGroup(), "rule__Spinner__Group__0");
					put(grammarAccess.getSpinnerAccess().getGroup_2(), "rule__Spinner__Group_2__0");
					put(grammarAccess.getCheckBoxAccess().getGroup(), "rule__CheckBox__Group__0");
					put(grammarAccess.getRadioGroupAccess().getGroup(), "rule__RadioGroup__Group__0");
					put(grammarAccess.getRatingBarAccess().getGroup(), "rule__RatingBar__Group__0");
					put(grammarAccess.getToggleButtonAccess().getGroup(), "rule__ToggleButton__Group__0");
					put(grammarAccess.getRadioButtonAccess().getGroup(), "rule__RadioButton__Group__0");
					put(grammarAccess.getPreferenceAccess().getGroup(), "rule__Preference__Group__0");
					put(grammarAccess.getPreferenceScreenAccess().getGroup(), "rule__PreferenceScreen__Group__0");
					put(grammarAccess.getPreferenceCategoryAccess().getGroup(), "rule__PreferenceCategory__Group__0");
					put(grammarAccess.getEditTextPreferenceAccess().getGroup(), "rule__EditTextPreference__Group__0");
					put(grammarAccess.getListPreferenceAccess().getGroup(), "rule__ListPreference__Group__0");
					put(grammarAccess.getCheckBoxPreferenceAccess().getGroup(), "rule__CheckBoxPreference__Group__0");
					put(grammarAccess.getRingtonePrefenceAccess().getGroup(), "rule__RingtonePrefence__Group__0");
					put(grammarAccess.getPreferenceAttributesAccess().getGroup(), "rule__PreferenceAttributes__Group__0");
					put(grammarAccess.getPreferenceAttributesAccess().getGroup_2(), "rule__PreferenceAttributes__Group_2__0");
					put(grammarAccess.getPreferenceAttributesAccess().getGroup_3(), "rule__PreferenceAttributes__Group_3__0");
					put(grammarAccess.getPreferenceAttributesAccess().getGroup_4(), "rule__PreferenceAttributes__Group_4__0");
					put(grammarAccess.getDialogPreferenceAttributesAccess().getGroup(), "rule__DialogPreferenceAttributes__Group__0");
					put(grammarAccess.getDialogPreferenceAttributesAccess().getGroup_0(), "rule__DialogPreferenceAttributes__Group_0__0");
					put(grammarAccess.getDialogPreferenceAttributesAccess().getGroup_1(), "rule__DialogPreferenceAttributes__Group_1__0");
					put(grammarAccess.getListPreferenceAttributesAccess().getGroup(), "rule__ListPreferenceAttributes__Group__0");
					put(grammarAccess.getAndroResModelRootAccess().getGroup(), "rule__AndroResModelRoot__Group__0");
					put(grammarAccess.getStringResourceAccess().getGroup(), "rule__StringResource__Group__0");
					put(grammarAccess.getIntegerResourceAccess().getGroup(), "rule__IntegerResource__Group__0");
					put(grammarAccess.getBooleanResourceAccess().getGroup(), "rule__BooleanResource__Group__0");
					put(grammarAccess.getColorResourceAccess().getGroup(), "rule__ColorResource__Group__0");
					put(grammarAccess.getDimensionResourceAccess().getGroup(), "rule__DimensionResource__Group__0");
					put(grammarAccess.getIntegerArrayResourceAccess().getGroup(), "rule__IntegerArrayResource__Group__0");
					put(grammarAccess.getIntegerArrayResourceAccess().getGroup_3(), "rule__IntegerArrayResource__Group_3__0");
					put(grammarAccess.getIntegerArrayResourceAccess().getGroup_3_1(), "rule__IntegerArrayResource__Group_3_1__0");
					put(grammarAccess.getIntegerArrayEntryAccess().getGroup(), "rule__IntegerArrayEntry__Group__0");
					put(grammarAccess.getIntegerArrayEntryAccess().getGroup_0(), "rule__IntegerArrayEntry__Group_0__0");
					put(grammarAccess.getStringArrayResourceAccess().getGroup(), "rule__StringArrayResource__Group__0");
					put(grammarAccess.getStringArrayResourceAccess().getGroup_3(), "rule__StringArrayResource__Group_3__0");
					put(grammarAccess.getStringArrayResourceAccess().getGroup_3_1(), "rule__StringArrayResource__Group_3_1__0");
					put(grammarAccess.getStringArrayEntryAccess().getGroup(), "rule__StringArrayEntry__Group__0");
					put(grammarAccess.getStringArrayEntryAccess().getGroup_0(), "rule__StringArrayEntry__Group_0__0");
					put(grammarAccess.getBitmapDrawableResourceAccess().getGroup(), "rule__BitmapDrawableResource__Group__0");
					put(grammarAccess.getTransitionDrawableResourceAccess().getGroup(), "rule__TransitionDrawableResource__Group__0");
					put(grammarAccess.getDimensionValueAccess().getGroup(), "rule__DimensionValue__Group__0");
					put(grammarAccess.getFLOATAccess().getGroup(), "rule__FLOAT__Group__0");
					put(grammarAccess.getFLOATAccess().getGroup_1(), "rule__FLOAT__Group_1__0");
					put(grammarAccess.getAndroTextModelRootAccess().getNameAssignment_0_1(), "rule__AndroTextModelRoot__NameAssignment_0_1");
					put(grammarAccess.getAndroTextModelRootAccess().getImportsAssignment_1(), "rule__AndroTextModelRoot__ImportsAssignment_1");
					put(grammarAccess.getAndroTextModelRootAccess().getActualModelRootAssignment_2(), "rule__AndroTextModelRoot__ActualModelRootAssignment_2");
					put(grammarAccess.getImportAccess().getImportedNamespaceAssignment_1(), "rule__Import__ImportedNamespaceAssignment_1");
					put(grammarAccess.getAndroGenModelRootAccess().getNameAssignment_1(), "rule__AndroGenModelRoot__NameAssignment_1");
					put(grammarAccess.getAndroGenModelRootAccess().getTargetApplicationsAssignment_3(), "rule__AndroGenModelRoot__TargetApplicationsAssignment_3");
					put(grammarAccess.getTargetApplicationAccess().getApplicationAssignment_1(), "rule__TargetApplication__ApplicationAssignment_1");
					put(grammarAccess.getTargetApplicationAccess().getProjectNameAssignment_4(), "rule__TargetApplication__ProjectNameAssignment_4");
					put(grammarAccess.getTargetApplicationAccess().getPackageNameAssignment_5_1(), "rule__TargetApplication__PackageNameAssignment_5_1");
					put(grammarAccess.getTargetApplicationAccess().getTargetAssignment_7(), "rule__TargetApplication__TargetAssignment_7");
					put(grammarAccess.getTargetApplicationAccess().getVersionAssignment_9(), "rule__TargetApplication__VersionAssignment_9");
					put(grammarAccess.getAndroidApplicationAccess().getNameAssignment_1(), "rule__AndroidApplication__NameAssignment_1");
					put(grammarAccess.getAndroidApplicationAccess().getDatarootAssignment_3_1(), "rule__AndroidApplication__DatarootAssignment_3_1");
					put(grammarAccess.getAndroidApplicationAccess().getMainActivityAssignment_4(), "rule__AndroidApplication__MainActivityAssignment_4");
					put(grammarAccess.getAndroidApplicationAccess().getModelElementsAssignment_5(), "rule__AndroidApplication__ModelElementsAssignment_5");
					put(grammarAccess.getActivityAccess().getNameAssignment_1(), "rule__Activity__NameAssignment_1");
					put(grammarAccess.getActivityAccess().getLayoutAssignment_3(), "rule__Activity__LayoutAssignment_3");
					put(grammarAccess.getTabActivityAccess().getNameAssignment_1(), "rule__TabActivity__NameAssignment_1");
					put(grammarAccess.getAndroDataModelRootAccess().getNameAssignment_1(), "rule__AndroDataModelRoot__NameAssignment_1");
					put(grammarAccess.getAndroDataModelRootAccess().getEntitiesAssignment_3(), "rule__AndroDataModelRoot__EntitiesAssignment_3");
					put(grammarAccess.getEntityAccess().getNameAssignment_1(), "rule__Entity__NameAssignment_1");
					put(grammarAccess.getEntityAccess().getSuperTypeAssignment_2_1(), "rule__Entity__SuperTypeAssignment_2_1");
					put(grammarAccess.getEntityAccess().getPropertiesAssignment_4(), "rule__Entity__PropertiesAssignment_4");
					put(grammarAccess.getPropertyAccess().getNameAssignment_0(), "rule__Property__NameAssignment_0");
					put(grammarAccess.getPropertyAccess().getTypeAssignment_2(), "rule__Property__TypeAssignment_2");
					put(grammarAccess.getDataTypesRefAccess().getTypeAssignment(), "rule__DataTypesRef__TypeAssignment");
					put(grammarAccess.getEntityTypeRefAccess().getTypeAssignment(), "rule__EntityTypeRef__TypeAssignment");
					put(grammarAccess.getAndroGuiModelRootAccess().getNameAssignment_1(), "rule__AndroGuiModelRoot__NameAssignment_1");
					put(grammarAccess.getAndroGuiModelRootAccess().getRootLayoutAssignment_3(), "rule__AndroGuiModelRoot__RootLayoutAssignment_3");
					put(grammarAccess.getAbsoluteLayoutAccess().getNameAssignment_1(), "rule__AbsoluteLayout__NameAssignment_1");
					put(grammarAccess.getAbsoluteLayoutAccess().getLayoutStyleAssignment_2(), "rule__AbsoluteLayout__LayoutStyleAssignment_2");
					put(grammarAccess.getAbsoluteLayoutAccess().getElementsAssignment_4(), "rule__AbsoluteLayout__ElementsAssignment_4");
					put(grammarAccess.getLinearLayoutAccess().getNameAssignment_1(), "rule__LinearLayout__NameAssignment_1");
					put(grammarAccess.getLinearLayoutAccess().getOrientationAssignment_2_0(), "rule__LinearLayout__OrientationAssignment_2_0");
					put(grammarAccess.getLinearLayoutAccess().getLayoutStyleAssignment_3(), "rule__LinearLayout__LayoutStyleAssignment_3");
					put(grammarAccess.getLinearLayoutAccess().getElementsAssignment_5(), "rule__LinearLayout__ElementsAssignment_5");
					put(grammarAccess.getFrameLayoutAccess().getNameAssignment_1(), "rule__FrameLayout__NameAssignment_1");
					put(grammarAccess.getFrameLayoutAccess().getLayoutStyleAssignment_2(), "rule__FrameLayout__LayoutStyleAssignment_2");
					put(grammarAccess.getFrameLayoutAccess().getElementsAssignment_4(), "rule__FrameLayout__ElementsAssignment_4");
					put(grammarAccess.getRelativeLayoutAccess().getNameAssignment_1(), "rule__RelativeLayout__NameAssignment_1");
					put(grammarAccess.getRelativeLayoutAccess().getLayoutStyleAssignment_2(), "rule__RelativeLayout__LayoutStyleAssignment_2");
					put(grammarAccess.getRelativeLayoutAccess().getElementsAssignment_4(), "rule__RelativeLayout__ElementsAssignment_4");
					put(grammarAccess.getTextViewAccess().getNameAssignment_1(), "rule__TextView__NameAssignment_1");
					put(grammarAccess.getTextViewAccess().getTextAssignment_2(), "rule__TextView__TextAssignment_2");
					put(grammarAccess.getTextViewAccess().getLayoutStyleAssignment_3(), "rule__TextView__LayoutStyleAssignment_3");
					put(grammarAccess.getEditTextAccess().getNameAssignment_1(), "rule__EditText__NameAssignment_1");
					put(grammarAccess.getEditTextAccess().getTextAssignment_2(), "rule__EditText__TextAssignment_2");
					put(grammarAccess.getEditTextAccess().getLayoutStyleAssignment_3(), "rule__EditText__LayoutStyleAssignment_3");
					put(grammarAccess.getButtonAccess().getNameAssignment_1(), "rule__Button__NameAssignment_1");
					put(grammarAccess.getButtonAccess().getTextAssignment_2(), "rule__Button__TextAssignment_2");
					put(grammarAccess.getButtonAccess().getLayoutStyleAssignment_3(), "rule__Button__LayoutStyleAssignment_3");
					put(grammarAccess.getListViewAccess().getNameAssignment_1(), "rule__ListView__NameAssignment_1");
					put(grammarAccess.getListViewAccess().getLayoutStyleAssignment_2(), "rule__ListView__LayoutStyleAssignment_2");
					put(grammarAccess.getListViewAccess().getEntriesAssignment_4_1(), "rule__ListView__EntriesAssignment_4_1");
					put(grammarAccess.getListViewAccess().getLayoutAssignment_5_1(), "rule__ListView__LayoutAssignment_5_1");
					put(grammarAccess.getSpinnerAccess().getNameAssignment_1(), "rule__Spinner__NameAssignment_1");
					put(grammarAccess.getSpinnerAccess().getEntriesAssignment_2_1(), "rule__Spinner__EntriesAssignment_2_1");
					put(grammarAccess.getSpinnerAccess().getLayoutStyleAssignment_3(), "rule__Spinner__LayoutStyleAssignment_3");
					put(grammarAccess.getCheckBoxAccess().getNameAssignment_1(), "rule__CheckBox__NameAssignment_1");
					put(grammarAccess.getCheckBoxAccess().getTextAssignment_2(), "rule__CheckBox__TextAssignment_2");
					put(grammarAccess.getCheckBoxAccess().getLayoutStyleAssignment_3(), "rule__CheckBox__LayoutStyleAssignment_3");
					put(grammarAccess.getRadioGroupAccess().getNameAssignment_1(), "rule__RadioGroup__NameAssignment_1");
					put(grammarAccess.getRadioGroupAccess().getOrientationAssignment_2_0(), "rule__RadioGroup__OrientationAssignment_2_0");
					put(grammarAccess.getRadioGroupAccess().getLayoutStyleAssignment_3(), "rule__RadioGroup__LayoutStyleAssignment_3");
					put(grammarAccess.getRadioGroupAccess().getRadiobuttonsAssignment_5(), "rule__RadioGroup__RadiobuttonsAssignment_5");
					put(grammarAccess.getRatingBarAccess().getNameAssignment_1(), "rule__RatingBar__NameAssignment_1");
					put(grammarAccess.getRatingBarAccess().getNumStarsAssignment_2(), "rule__RatingBar__NumStarsAssignment_2");
					put(grammarAccess.getRatingBarAccess().getLayoutStyleAssignment_3(), "rule__RatingBar__LayoutStyleAssignment_3");
					put(grammarAccess.getToggleButtonAccess().getNameAssignment_1(), "rule__ToggleButton__NameAssignment_1");
					put(grammarAccess.getToggleButtonAccess().getTextOnAssignment_3(), "rule__ToggleButton__TextOnAssignment_3");
					put(grammarAccess.getToggleButtonAccess().getTextOffAssignment_5(), "rule__ToggleButton__TextOffAssignment_5");
					put(grammarAccess.getToggleButtonAccess().getLayoutStyleAssignment_6(), "rule__ToggleButton__LayoutStyleAssignment_6");
					put(grammarAccess.getRadioButtonAccess().getNameAssignment_1(), "rule__RadioButton__NameAssignment_1");
					put(grammarAccess.getRadioButtonAccess().getTextAssignment_2(), "rule__RadioButton__TextAssignment_2");
					put(grammarAccess.getRadioButtonAccess().getLayoutStyleAssignment_3(), "rule__RadioButton__LayoutStyleAssignment_3");
					put(grammarAccess.getPreferenceAccess().getTitleAssignment_1(), "rule__Preference__TitleAssignment_1");
					put(grammarAccess.getPreferenceAccess().getPreferenceAttributesAssignment_3(), "rule__Preference__PreferenceAttributesAssignment_3");
					put(grammarAccess.getPreferenceScreenAccess().getNameAssignment_1(), "rule__PreferenceScreen__NameAssignment_1");
					put(grammarAccess.getPreferenceScreenAccess().getTitleAssignment_2(), "rule__PreferenceScreen__TitleAssignment_2");
					put(grammarAccess.getPreferenceScreenAccess().getPreferenceAttributesAssignment_4(), "rule__PreferenceScreen__PreferenceAttributesAssignment_4");
					put(grammarAccess.getPreferenceScreenAccess().getPreferencesAssignment_5(), "rule__PreferenceScreen__PreferencesAssignment_5");
					put(grammarAccess.getPreferenceCategoryAccess().getTitleAssignment_1(), "rule__PreferenceCategory__TitleAssignment_1");
					put(grammarAccess.getPreferenceCategoryAccess().getPreferencesAssignment_3(), "rule__PreferenceCategory__PreferencesAssignment_3");
					put(grammarAccess.getEditTextPreferenceAccess().getTitleAssignment_1(), "rule__EditTextPreference__TitleAssignment_1");
					put(grammarAccess.getEditTextPreferenceAccess().getPreferenceAttributesAssignment_3(), "rule__EditTextPreference__PreferenceAttributesAssignment_3");
					put(grammarAccess.getEditTextPreferenceAccess().getDialogPreferenceAttributesAssignment_4(), "rule__EditTextPreference__DialogPreferenceAttributesAssignment_4");
					put(grammarAccess.getListPreferenceAccess().getTitleAssignment_1(), "rule__ListPreference__TitleAssignment_1");
					put(grammarAccess.getListPreferenceAccess().getPreferenceAttributesAssignment_3(), "rule__ListPreference__PreferenceAttributesAssignment_3");
					put(grammarAccess.getListPreferenceAccess().getDialogPreferenceAttributesAssignment_4(), "rule__ListPreference__DialogPreferenceAttributesAssignment_4");
					put(grammarAccess.getListPreferenceAccess().getListPreferenceAttributesAssignment_5(), "rule__ListPreference__ListPreferenceAttributesAssignment_5");
					put(grammarAccess.getCheckBoxPreferenceAccess().getTitleAssignment_1(), "rule__CheckBoxPreference__TitleAssignment_1");
					put(grammarAccess.getCheckBoxPreferenceAccess().getPreferenceAttributesAssignment_3(), "rule__CheckBoxPreference__PreferenceAttributesAssignment_3");
					put(grammarAccess.getRingtonePrefenceAccess().getTitleAssignment_1(), "rule__RingtonePrefence__TitleAssignment_1");
					put(grammarAccess.getRingtonePrefenceAccess().getPreferenceAttributesAssignment_3(), "rule__RingtonePrefence__PreferenceAttributesAssignment_3");
					put(grammarAccess.getPreferenceAttributesAccess().getKeyAssignment_1(), "rule__PreferenceAttributes__KeyAssignment_1");
					put(grammarAccess.getPreferenceAttributesAccess().getSummaryAssignment_2_1(), "rule__PreferenceAttributes__SummaryAssignment_2_1");
					put(grammarAccess.getPreferenceAttributesAccess().getEnabledAssignment_3_1(), "rule__PreferenceAttributes__EnabledAssignment_3_1");
					put(grammarAccess.getPreferenceAttributesAccess().getPersistentAssignment_4_1(), "rule__PreferenceAttributes__PersistentAssignment_4_1");
					put(grammarAccess.getDialogPreferenceAttributesAccess().getDialogTitleAssignment_0_1(), "rule__DialogPreferenceAttributes__DialogTitleAssignment_0_1");
					put(grammarAccess.getDialogPreferenceAttributesAccess().getDefaultValueAssignment_1_1(), "rule__DialogPreferenceAttributes__DefaultValueAssignment_1_1");
					put(grammarAccess.getListPreferenceAttributesAccess().getEntriesAssignment_1(), "rule__ListPreferenceAttributes__EntriesAssignment_1");
					put(grammarAccess.getListPreferenceAttributesAccess().getEntryValuesAssignment_3(), "rule__ListPreferenceAttributes__EntryValuesAssignment_3");
					put(grammarAccess.getAndroResModelRootAccess().getNameAssignment_1(), "rule__AndroResModelRoot__NameAssignment_1");
					put(grammarAccess.getAndroResModelRootAccess().getResourcesAssignment_3(), "rule__AndroResModelRoot__ResourcesAssignment_3");
					put(grammarAccess.getStringResourceAccess().getNameAssignment_0(), "rule__StringResource__NameAssignment_0");
					put(grammarAccess.getStringResourceAccess().getValueAssignment_2(), "rule__StringResource__ValueAssignment_2");
					put(grammarAccess.getIntegerResourceAccess().getNameAssignment_0(), "rule__IntegerResource__NameAssignment_0");
					put(grammarAccess.getIntegerResourceAccess().getValueAssignment_2(), "rule__IntegerResource__ValueAssignment_2");
					put(grammarAccess.getBooleanResourceAccess().getNameAssignment_0(), "rule__BooleanResource__NameAssignment_0");
					put(grammarAccess.getBooleanResourceAccess().getValueAssignment_2(), "rule__BooleanResource__ValueAssignment_2");
					put(grammarAccess.getColorResourceAccess().getNameAssignment_0(), "rule__ColorResource__NameAssignment_0");
					put(grammarAccess.getColorResourceAccess().getValueAssignment_2(), "rule__ColorResource__ValueAssignment_2");
					put(grammarAccess.getDimensionResourceAccess().getNameAssignment_0(), "rule__DimensionResource__NameAssignment_0");
					put(grammarAccess.getDimensionResourceAccess().getValueAssignment_2(), "rule__DimensionResource__ValueAssignment_2");
					put(grammarAccess.getIntegerArrayResourceAccess().getNameAssignment_1(), "rule__IntegerArrayResource__NameAssignment_1");
					put(grammarAccess.getIntegerArrayResourceAccess().getEntriesAssignment_3_0(), "rule__IntegerArrayResource__EntriesAssignment_3_0");
					put(grammarAccess.getIntegerArrayResourceAccess().getEntriesAssignment_3_1_1(), "rule__IntegerArrayResource__EntriesAssignment_3_1_1");
					put(grammarAccess.getIntegerArrayEntryAccess().getNameAssignment_0_0(), "rule__IntegerArrayEntry__NameAssignment_0_0");
					put(grammarAccess.getIntegerArrayEntryAccess().getValueAssignment_1(), "rule__IntegerArrayEntry__ValueAssignment_1");
					put(grammarAccess.getStringArrayResourceAccess().getNameAssignment_1(), "rule__StringArrayResource__NameAssignment_1");
					put(grammarAccess.getStringArrayResourceAccess().getEntriesAssignment_3_0(), "rule__StringArrayResource__EntriesAssignment_3_0");
					put(grammarAccess.getStringArrayResourceAccess().getEntriesAssignment_3_1_1(), "rule__StringArrayResource__EntriesAssignment_3_1_1");
					put(grammarAccess.getStringArrayEntryAccess().getNameAssignment_0_0(), "rule__StringArrayEntry__NameAssignment_0_0");
					put(grammarAccess.getStringArrayEntryAccess().getValueAssignment_1(), "rule__StringArrayEntry__ValueAssignment_1");
					put(grammarAccess.getBitmapDrawableResourceAccess().getNameAssignment_0(), "rule__BitmapDrawableResource__NameAssignment_0");
					put(grammarAccess.getBitmapDrawableResourceAccess().getFilenameAssignment_2(), "rule__BitmapDrawableResource__FilenameAssignment_2");
					put(grammarAccess.getTransitionDrawableResourceAccess().getNameAssignment_0(), "rule__TransitionDrawableResource__NameAssignment_0");
					put(grammarAccess.getTransitionDrawableResourceAccess().getFromAssignment_1(), "rule__TransitionDrawableResource__FromAssignment_1");
					put(grammarAccess.getTransitionDrawableResourceAccess().getToAssignment_3(), "rule__TransitionDrawableResource__ToAssignment_3");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			hu.bme.mit.androtext.lang.ui.contentassist.antlr.internal.InternalAndroTextDslParser typedParser = (hu.bme.mit.androtext.lang.ui.contentassist.antlr.internal.InternalAndroTextDslParser) parser;
			typedParser.entryRuleAndroTextModelRoot();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public AndroTextDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AndroTextDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
