/*
* generated by Xtext
*/
package hu.bme.mit.androtext.lang.ui.contentassist;

import hu.bme.mit.androtext.lang.ui.contentassist.AbstractAndroTextDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AndroTextDslProposalProvider extends AbstractAndroTextDslProposalProvider {

}
