/*
 * generated by Xtext
 */
package hu.bme.mit.androtext.lang.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AndroTextDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return hu.bme.mit.androtext.lang.ui.internal.AndroTextDslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return hu.bme.mit.androtext.lang.ui.internal.AndroTextDslActivator.getInstance().getInjector("hu.bme.mit.androtext.lang.AndroTextDsl");
	}
	
}
