/*
* generated by Xtext
*/
package hu.bme.mit.androtext.lang.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import hu.bme.mit.androtext.lang.services.AndroTextDslGrammarAccess;

public class AndroTextDslParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private AndroTextDslGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected hu.bme.mit.androtext.lang.parser.antlr.internal.InternalAndroTextDslParser createParser(XtextTokenStream stream) {
		return new hu.bme.mit.androtext.lang.parser.antlr.internal.InternalAndroTextDslParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "AndroTextModelRoot";
	}
	
	public AndroTextDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(AndroTextDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
