/*
* generated by Xtext
*/
package hu.bme.mit.androtext.lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class AndroTextDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("hu/bme/mit/androtext/lang/parser/antlr/internal/InternalAndroTextDsl.tokens");
	}
}
