/*
 * generated by Xtext
 */
package hu.bme.mit.androtext.lang;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class AndroTextDslRuntimeModule extends hu.bme.mit.androtext.lang.AbstractAndroTextDslRuntimeModule {

}
