/*
 * generated by Xtext
 */
package hu.bme.mit.androtext.lang.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AndroTextDslUiModule extends hu.bme.mit.androtext.lang.ui.AbstractAndroTextDslUiModule {
	public AndroTextDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
