<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="androTextDsl"
    nsURI="http://www.bme.hu/mit/androtext/lang/AndroTextDsl" nsPrefix="androTextDsl">
  <eClassifiers xsi:type="ecore:EClass" name="AndroTextModelRoot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualModelRoot" eType="#//ModelRoot"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroGenModelRoot" eSuperTypes="#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetApplications" upperBound="-1"
        eType="#//TargetApplication" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="#//AndroidApplication"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="#//ApiLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ApiLevel">
    <eLiterals name="API8" literal="Android 2.2"/>
    <eLiterals name="API9" value="1" literal="Android 2.3.1"/>
    <eLiterals name="API10" value="2" literal="Android 2.3.3"/>
    <eLiterals name="API11" value="3" literal="Android 3.0"/>
    <eLiterals name="API12" value="4" literal="Android 3.1"/>
    <eLiterals name="API14" value="5" literal="Android 4.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroidApplication" eSuperTypes="#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataroot" eType="#//AndroDataModelRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainActivity" eType="#//Activity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
        eType="#//AndroidApplicationModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroidApplicationModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//AndroidApplicationModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//ViewGroup"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="theme" eType="#//ActivityTheme"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActivityTheme">
    <eLiterals name="DIALOG" literal="DIALOG"/>
    <eLiterals name="NOTITLE" value="1" literal="NOTITLE"/>
    <eLiterals name="FULLSCREEN" value="2" literal="FULLSCREEN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tabs" upperBound="-1" eType="#//Tab"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tab">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listitem" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceActivity" eSuperTypes="#//AndroidApplicationModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//PreferenceScreen"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action"/>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeActivity" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//Activity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InvokeWebUrl" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroDataModelRoot" eSuperTypes="#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypesRef" eSuperTypes="#//TypeRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DataTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityTypeRef" eSuperTypes="#//TypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataTypes">
    <eLiterals name="STRING" literal="String"/>
    <eLiterals name="FLOAT" value="1" literal="float"/>
    <eLiterals name="BOOLEAN" value="2" literal="boolean"/>
    <eLiterals name="INT" value="3" literal="int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroGuiModelRoot" eSuperTypes="#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="roots" upperBound="-1"
        eType="#//View" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutStyle" eType="#//LayoutDimensionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewGroup" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//View" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutParams">
    <eStructuralFeatures xsi:type="ecore:EReference" name="weight" eType="#//IntegerPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marginLeft" eType="#//DimensionPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marginTop" eType="#//DimensionPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marginRight" eType="#//DimensionPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marginBottom" eType="#//DimensionPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignParentleft" eType="#//BooleanPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignParentTop" eType="#//BooleanPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignParentRight" eType="#//BooleanPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignParentBottom" eType="#//BooleanPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignTop" eType="#//View"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignBottom" eType="#//View"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignLeft" eType="#//View"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="below" eType="#//View"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="above" eType="#//View"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toLeftOf" eType="#//View"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRightOf" eType="#//View"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="centerHorizontal" eType="#//BooleanPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="centerInParent" eType="#//BooleanPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="centerVertical" eType="#//BooleanPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundAttribute" eType="#//BackgroundAttribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutGravityAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gravity" unique="false"
        upperBound="-1" eType="#//LayoutGravityKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LayoutGravityKind">
    <eLiterals name="top" literal="top"/>
    <eLiterals name="bottom" value="1" literal="bottom"/>
    <eLiterals name="left" value="2" literal="left"/>
    <eLiterals name="right" value="3" literal="right"/>
    <eLiterals name="center" value="4" literal="center"/>
    <eLiterals name="center_vertical" value="5" literal="center_vertical"/>
    <eLiterals name="center_horizontal" value="6" literal="center_horizontal"/>
    <eLiterals name="fill" value="7" literal="fill"/>
    <eLiterals name="fill_vertical" value="8" literal="fill_vertical"/>
    <eLiterals name="fill_horizontal" value="9" literal="fill_horizontal"/>
    <eLiterals name="clip_vertical" value="10" literal="clip_vertical"/>
    <eLiterals name="clip_horizontal" value="11" literal="clip_horizontal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LayoutDimensionKind">
    <eLiterals name="FILL" literal="fill"/>
    <eLiterals name="WRAP" value="1" literal="wrap"/>
    <eLiterals name="FILL_WRAP" value="2" literal="fill&amp;wrap"/>
    <eLiterals name="WRAP_FILL" value="3" literal="wrap&amp;fill"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbsoluteLayout" eSuperTypes="#//ViewGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinearLayout" eSuperTypes="#//ViewGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vertical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutParams" eType="#//LinearLayoutParams"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinearLayoutParams">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutParams" eType="#//LayoutParams"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gravity" eType="#//LayoutGravityAttribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrameLayout" eSuperTypes="#//ViewGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeLayout" eSuperTypes="#//ViewGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="GridLayout" eSuperTypes="#//ViewGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableLayout" eSuperTypes="#//ViewGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleView" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="Gallery" eSuperTypes="#//SimpleView"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpandableListView" eSuperTypes="#//SimpleView"/>
  <eClassifiers xsi:type="ecore:EClass" name="WebView" eSuperTypes="#//SimpleView"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImageView" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" eType="#//DrawableResource"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextView" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gravityAttribute" eType="#//GravityAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textSizeAttribute" eType="#//TextSizeAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutParams" eType="#//LayoutParams"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GravityAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gravity" eType="#//LayoutGravityKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextSizeAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="textSize" eType="#//DimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BackgroundAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="background" eType="#//AnyDrawablePropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditText" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gravityAttribute" eType="#//GravityAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textSizeAttribute" eType="#//TextSizeAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutParams" eType="#//LayoutParams"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutParams" eType="#//LayoutParams"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListView" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" eType="#//ArrayResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GridView" eSuperTypes="#//SimpleView"/>
  <eClassifiers xsi:type="ecore:EClass" name="Spinner" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" eType="#//ArrayResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckBox" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RadioGroup" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="radiobuttons" upperBound="-1"
        eType="#//RadioButton" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RatingBar" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numStars" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToggleButton" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textOn" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textOff" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RadioButton">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="layoutStyle" eType="#//LayoutDimensionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckedTextView" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutoCompleteTextView" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" eType="#//StringArrayResource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMulti" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Preference" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceAttributes" eType="#//PreferenceAttributes"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceScreen" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceAttributes" eType="#//PreferenceAttributes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferences" upperBound="-1"
        eType="#//AbstractPreference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceCategory" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferences" upperBound="-1"
        eType="#//AbstractPreference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditTextPreference" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceAttributes" eType="#//PreferenceAttributes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dialogPreferenceAttributes"
        eType="#//DialogPreferenceAttributes" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListPreference" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceAttributes" eType="#//PreferenceAttributes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dialogPreferenceAttributes"
        eType="#//DialogPreferenceAttributes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listPreferenceAttributes"
        eType="#//ListPreferenceAttributes" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckBoxPreference" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceAttributes" eType="#//PreferenceAttributes"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RingtonePrefence" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceAttributes" eType="#//PreferenceAttributes"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceAttributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DialogPreferenceAttributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dialogTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListPreferenceAttributes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" eType="#//StringArrayEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryValues" eType="#//StringArrayEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnyDrawablePropertyValue" eSuperTypes="#//PropertyValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorPropertyValue" eSuperTypes="#//AnyDrawablePropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//DimensionValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawableResourceLink" eSuperTypes="#//AnyDrawablePropertyValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="LocalDrawableResourceLink" eSuperTypes="#//DrawableResourceLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//DrawableResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDrawableResourceLink" eSuperTypes="#//DrawableResourceLink">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalResource" eType="#//AndroidDrawableResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AndroidDrawableResource">
    <eLiterals name="android_editbox_background" literal="android_editbox_background"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringResourceLink" eSuperTypes="#//StringPropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//StringResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerResourceLink" eSuperTypes="#//IntegerPropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//IntegerResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanResourceLink" eSuperTypes="#//BooleanPropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//BooleanResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorResourceLink" eSuperTypes="#//ColorPropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//ColorResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionResourceLink" eSuperTypes="#//DimensionPropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//DimensionResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroResModelRoot" eSuperTypes="#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//DimensionValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayResource" eSuperTypes="#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerArrayResource" eSuperTypes="#//ArrayResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//IntegerArrayEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerArrayEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringArrayResource" eSuperTypes="#//ArrayResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//StringArrayEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringArrayEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawableResource" eSuperTypes="#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="BitmapDrawableResource" eSuperTypes="#//DrawableResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionDrawableResource" eSuperTypes="#//DrawableResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//BitmapDrawableResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//BitmapDrawableResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metric" eType="#//DimensionMetric"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DimensionMetric">
    <eLiterals name="dp" literal="dp"/>
    <eLiterals name="sp" value="1" literal="sp"/>
    <eLiterals name="pt" value="2" literal="pt"/>
    <eLiterals name="px" value="3" literal="px"/>
    <eLiterals name="mm" value="4" literal="mm"/>
    <eLiterals name="in" value="5" literal="in"/>
  </eClassifiers>
</ecore:EPackage>
