/*
* generated by Xtext
*/
package hu.bme.mit.androtext.lang.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class AndroTextDslOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
