<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="androTextDsl"
    nsURI="http://www.bme.hu/mit/androtext/lang/AndroTextDsl" nsPrefix="androTextDsl">
  <eClassifiers xsi:type="ecore:EClass" name="AndroTextModelRoot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="imports" upperBound="-1"
        eType="#//Import" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="actualModelRoot" eType="#//ModelRoot"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelRoot"/>
  <eClassifiers xsi:type="ecore:EClass" name="Import">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroGenModelRoot" eSuperTypes="#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetApplications" upperBound="-1"
        eType="#//TargetApplication" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetApplication">
    <eStructuralFeatures xsi:type="ecore:EReference" name="application" eType="#//AndroidApplication"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="packageName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" eType="#//ApiLevel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ApiLevel">
    <eLiterals name="API8" literal="Android 2.2"/>
    <eLiterals name="API9" value="1" literal="Android 2.3.1"/>
    <eLiterals name="API10" value="2" literal="Android 2.3.3"/>
    <eLiterals name="API11" value="3" literal="Android 3.0"/>
    <eLiterals name="API12" value="4" literal="Android 3.1"/>
    <eLiterals name="API14" value="5" literal="Android 4.0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroidApplication" eSuperTypes="#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataroot" eType="#//AndroDataModelRoot"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainActivity" eType="#//Activity"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelElements" upperBound="-1"
        eType="#//AndroidApplicationModelElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroidApplicationModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Activity" eSuperTypes="#//AndroidApplicationModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//View"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="theme" eType="#//ActivityTheme"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ActivityTheme">
    <eLiterals name="DIALOG" literal="DIALOG"/>
    <eLiterals name="NOTITLEBAR" value="1" literal="NOTITLEBAR"/>
    <eLiterals name="FULLSCREEN" value="2" literal="FULLSCREEN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tabs" upperBound="-1" eType="#//Tab"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tab">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tag" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="activity" eType="#//Activity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drawable" eType="#//TabDrawableResourceLink"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="listitem" eType="#//View"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contentProvider" eType="#//ContentProvider"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceActivity" eSuperTypes="#//AndroidApplicationModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//PreferenceScreen"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContentProvider"/>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceContentProvider" eSuperTypes="#//ContentProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//ArrayResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroDataModelRoot" eSuperTypes="#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//Entity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="superType" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//TypeRef"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypeRef"/>
  <eClassifiers xsi:type="ecore:EClass" name="DataTypesRef" eSuperTypes="#//TypeRef">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DataTypes"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityTypeRef" eSuperTypes="#//TypeRef">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataTypes">
    <eLiterals name="STRING" literal="String"/>
    <eLiterals name="FLOAT" value="1" literal="float"/>
    <eLiterals name="BOOLEAN" value="2" literal="boolean"/>
    <eLiterals name="INT" value="3" literal="int"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroGuiModelRoot" eSuperTypes="#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="roots" upperBound="-1"
        eType="#//View" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutAttributes" upperBound="-1"
        eType="#//LayoutProperties" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="View">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutStyle" eType="#//LayoutStyle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutProperties" eType="#//LayoutProperties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ViewGroup" eSuperTypes="#//View">
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" upperBound="-1"
        eType="#//View" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutProperties">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weightAttribute" eType="#//WeightAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marginLeftAttribute" eType="#//MarginLeftAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marginTopAttribute" eType="#//MarginTopAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marginRightAttribute" eType="#//MarginRightAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="marginBottomAttribute"
        eType="#//MarginBottomAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignParentLeftAttribute"
        eType="#//AlignParentLeftAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignParentTopAttribute"
        eType="#//AlignParentTopAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignParentRightAttribute"
        eType="#//AlignParentRightAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignParentBottomAttribute"
        eType="#//AlignParentBottomAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignTopAttribute" eType="#//AlignTopAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignBottomAttribute" eType="#//AlignBottomAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignLeftAttribute" eType="#//AlignLeftAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="belowAttribute" eType="#//BelowAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="aboveAttribute" eType="#//AboveAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toLeftOfAttribute" eType="#//ToLeftOfAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRightOfAttribute" eType="#//ToRightOfAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="centerHorizontalAttribute"
        eType="#//CenterHorizontalAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="centerInParentAttribute"
        eType="#//CenterInParentAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="centerVerticalAttribute"
        eType="#//CenterVerticalAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnAttribute" eType="#//ColumnAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="spanAttribute" eType="#//SpanAttribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutStyle"/>
  <eClassifiers xsi:type="ecore:EClass" name="RegularLayoutStyle" eSuperTypes="#//LayoutStyle">
    <eStructuralFeatures xsi:type="ecore:EReference" name="width" eType="#//LayoutDimensionPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="height" eType="#//LayoutDimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FastLayoutStyle" eSuperTypes="#//LayoutStyle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//FastLayoutDimensionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbsoluteLayout" eSuperTypes="#//ViewGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="LinearLayout" eSuperTypes="#//ViewGroup">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vertical" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gravity" eType="#//GravityAttribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrameLayout" eSuperTypes="#//ViewGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="RelativeLayout" eSuperTypes="#//ViewGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="GridLayout" eSuperTypes="#//ViewGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="TableLayout" eSuperTypes="#//ViewGroup">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collapseColumnsAttribute"
        eType="#//CollapseColumnsAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="shrinkColumnsAttribute"
        eType="#//ShrinkColumnsAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stretchColumnsAttribute"
        eType="#//StretchColumnsAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TableRow" eSuperTypes="#//ViewGroup"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleView" eSuperTypes="#//View"/>
  <eClassifiers xsi:type="ecore:EClass" name="ViewElement" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundAttribute" eType="#//BackgroundAttribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextView" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widthAttribute" eType="#//WidthAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heightAttribute" eType="#//HeightAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundAttribute" eType="#//BackgroundAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clickableAttribute" eType="#//ClickableAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadeScrollBarsAttribute"
        eType="#//FadeScrollBarsAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isScrollContainerAttribute"
        eType="#//IsScrollContainerAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="autoLinkAttribute" eType="#//AutoLinkAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="autoTextAttribute" eType="#//AutoTextAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capitalizeAttribute" eType="#//CapitalizeAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="digitsAttribute" eType="#//DigitsAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editableAttribute" eType="#//EditableAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hintAttribute" eType="#//HintAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="numericAttribute" eType="#//NumericAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passwordAttribute" eType="#//PasswordAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="phoneNumberAttribute" eType="#//PhoneNumberAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleLineAttribute" eType="#//SingleLineAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textColorAttribute" eType="#//TextColorAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typefaceAttribute" eType="#//TypefaceAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textStyleAttribute" eType="#//TextStyleAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gravityAttribute" eType="#//GravityAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textSizeAttribute" eType="#//TextSizeAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paddingAttribute" eType="#//PaddingAttribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditText" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widthAttribute" eType="#//WidthAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heightAttribute" eType="#//HeightAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundAttribute" eType="#//BackgroundAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clickableAttribute" eType="#//ClickableAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadeScrollBarsAttribute"
        eType="#//FadeScrollBarsAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isScrollContainerAttribute"
        eType="#//IsScrollContainerAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="autoLinkAttribute" eType="#//AutoLinkAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="autoTextAttribute" eType="#//AutoTextAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="capitalizeAttribute" eType="#//CapitalizeAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="digitsAttribute" eType="#//DigitsAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="editableAttribute" eType="#//EditableAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hintAttribute" eType="#//HintAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="numericAttribute" eType="#//NumericAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="passwordAttribute" eType="#//PasswordAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="phoneNumberAttribute" eType="#//PhoneNumberAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleLineAttribute" eType="#//SingleLineAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textColorAttribute" eType="#//TextColorAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="typefaceAttribute" eType="#//TypefaceAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textStyleAttribute" eType="#//TextStyleAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gravityAttribute" eType="#//GravityAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textSizeAttribute" eType="#//TextSizeAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="paddingAttribute" eType="#//PaddingAttribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widthAttribute" eType="#//WidthAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heightAttribute" eType="#//HeightAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundAttribute" eType="#//BackgroundAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clickableAttribute" eType="#//ClickableAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hintAttribute" eType="#//HintAttribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Gallery" eSuperTypes="#//SimpleView"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExpandableListView" eSuperTypes="#//SimpleView"/>
  <eClassifiers xsi:type="ecore:EClass" name="WebView" eSuperTypes="#//SimpleView"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImageView" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="src" eType="#//AnyDrawablePropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widthAttribute" eType="#//WidthAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heightAttribute" eType="#//HeightAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundAttribute" eType="#//BackgroundAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clickableAttribute" eType="#//ClickableAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadeScrollBarsAttribute"
        eType="#//FadeScrollBarsAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isScrollContainerAttribute"
        eType="#//IsScrollContainerAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListView" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entriesAttribute" eType="#//EntriesAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layout" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GridView" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnWidthAttribute" eType="#//ColumnWidthAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="horizontalSpacingAttribute"
        eType="#//HorizontalSpacingAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="verticalSpacingAttribute"
        eType="#//VerticalSpacingAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="numColumnsAttribute" eType="#//NumColumnsAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stretchModeAttribute" eType="#//StretchModeAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="gravityAttribute" eType="#//GravityAttribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Spinner" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entriesAttribute" eType="#//EntriesAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="widthAttribute" eType="#//WidthAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heightAttribute" eType="#//HeightAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="backgroundAttribute" eType="#//BackgroundAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clickableAttribute" eType="#//ClickableAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadeScrollBarsAttribute"
        eType="#//FadeScrollBarsAttribute" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isScrollContainerAttribute"
        eType="#//IsScrollContainerAttribute" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckBox" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="text" eType="#//StringPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RadioGroup" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="radiobuttons" upperBound="-1"
        eType="#//RadioButton" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RatingBar" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="numStars" eType="#//IntegerPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToggleButton" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="textOn" eType="#//StringPropertyValue"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textOff" eType="#//StringPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RadioButton">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutStyle" eType="#//LayoutStyle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="layoutProperties" eType="#//LayoutProperties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckedTextView" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutoCompleteTextView" eSuperTypes="#//SimpleView">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entriesAttribute" eType="#//EntriesAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listItem" eType="#//View"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="multi" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="title" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Preference" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceAttributes" eType="#//PreferenceAttributes"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceScreen" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceAttributes" eType="#//PreferenceAttributes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferences" upperBound="-1"
        eType="#//AbstractPreference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceCategory" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferences" upperBound="-1"
        eType="#//AbstractPreference" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditTextPreference" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceAttributes" eType="#//PreferenceAttributes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dialogPreferenceAttributes"
        eType="#//DialogPreferenceAttributes" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListPreference" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceAttributes" eType="#//PreferenceAttributes"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dialogPreferenceAttributes"
        eType="#//DialogPreferenceAttributes" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="listPreferenceAttributes"
        eType="#//ListPreferenceAttributes" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CheckBoxPreference" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceAttributes" eType="#//PreferenceAttributes"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RingtonePrefence" eSuperTypes="#//AbstractPreference">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preferenceAttributes" eType="#//PreferenceAttributes"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceAttributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="summary" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="persistent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DialogPreferenceAttributes">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dialogTitle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ListPreferenceAttributes">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entriesAttribute" eType="#//EntriesAttribute"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entryValues" eType="#//StringArrayEntry"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SpanAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="span" eType="#//IntegerPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="column" eType="#//IntegerPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CenterVerticalAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="centerVertical" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CenterInParentAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="centerInParent" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CenterHorizontalAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="centerHorizontal" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToRightOfAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toRightOf" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToLeftOfAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="toLeftOf" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AboveAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="above" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BelowAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="below" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlignLeftAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignLeft" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlignBottomAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignBottom" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlignTopAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignTop" eType="#//View"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlignParentLeftAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignParentLeft" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlignParentTopAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignParentTop" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlignParentRightAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignParentRight" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlignParentBottomAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="alignParentBottom" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarginBottomAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="marginBottom" eType="#//DimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarginRightAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="marginRight" eType="#//DimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarginTopAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="marginTop" eType="#//DimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WeightAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="weight" eType="#//IntegerPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MarginLeftAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="marginLeft" eType="#//DimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextStyleAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="textStyle" unique="false"
        upperBound="-1" eType="#//TextStyleKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TypefaceAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="typeface" eType="#//TypefaceKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextColorAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="textColor" eType="#//ColorPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleLineAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="singleLine" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhoneNumberAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="phoneNumber" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PasswordAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="password" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumericAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="numeric" unique="false"
        upperBound="-1" eType="#//NumericKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="NumericKind">
    <eLiterals name="integer" literal="integer"/>
    <eLiterals name="signed" value="1" literal="signed"/>
    <eLiterals name="decimal" value="2" literal="decimal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HintAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hint" eType="#//StringPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TypefaceKind">
    <eLiterals name="normal" literal="normal"/>
    <eLiterals name="sans" value="1" literal="sans"/>
    <eLiterals name="serif" value="2" literal="serif"/>
    <eLiterals name="monospace" value="3" literal="monospace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TextStyleKind">
    <eLiterals name="normal" literal="normal"/>
    <eLiterals name="bold" value="1" literal="bold"/>
    <eLiterals name="italic" value="2" literal="italic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EditableAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="editable" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DigitsAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="digits" eType="#//StringPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapitalizeAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capitalize" eType="#//CapitalizeKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CapitalizeKind">
    <eLiterals name="none" literal="none"/>
    <eLiterals name="sentences" value="1" literal="sentences"/>
    <eLiterals name="words" value="2" literal="words"/>
    <eLiterals name="characters" value="3" literal="characters"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutoTextAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="autoText" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IsScrollContainerAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isScrollContainer" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FadeScrollBarsAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fadeScrollBars" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClickableAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clickable" eType="#//BooleanPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AutoLinkAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="all" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autoLinkMask" unique="false"
        upperBound="-1" eType="#//AutoLinkKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AutoLinkKind">
    <eLiterals name="web" literal="web"/>
    <eLiterals name="email" value="1" literal="email"/>
    <eLiterals name="phone" value="2" literal="phone"/>
    <eLiterals name="map" value="3" literal="map"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WidthAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="width" eType="#//DimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HeightAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="height" eType="#//DimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PaddingAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="padding" eType="#//DimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GravityAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gravity" unique="false"
        upperBound="-1" eType="#//GravityKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextSizeAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="textSize" eType="#//DimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BackgroundAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="background" eType="#//AnyDrawablePropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColumnWidthAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="columnWidth" eType="#//DimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HorizontalSpacingAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="horizontalSpacing" eType="#//DimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NumColumnsAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="autofit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="numColumns" eType="#//IntegerPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StretchModeAttribute">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stretchMode" eType="#//StretchModeKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StretchModeKind">
    <eLiterals name="none" literal="none"/>
    <eLiterals name="spacingWidth" value="1" literal="spacingWidth"/>
    <eLiterals name="columnWidth" value="2" literal="columnWidth"/>
    <eLiterals name="spacingWidthUniform" value="3" literal="spacingWidthUniform"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VerticalSpacingAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="verticalSpacing" eType="#//DimensionPropertyValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntriesAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" eType="#//ArrayResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StretchColumnsAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="stretchColumns" upperBound="-1"
        eType="#//IntegerPropertyValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ShrinkColumnsAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="shrinkColumns" upperBound="-1"
        eType="#//IntegerPropertyValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollapseColumnsAttribute">
    <eStructuralFeatures xsi:type="ecore:EReference" name="collapseColumns" upperBound="-1"
        eType="#//IntegerPropertyValue" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="GravityKind">
    <eLiterals name="top" literal="top"/>
    <eLiterals name="bottom" value="1" literal="bottom"/>
    <eLiterals name="left" value="2" literal="left"/>
    <eLiterals name="right" value="3" literal="right"/>
    <eLiterals name="center" value="4" literal="center"/>
    <eLiterals name="center_vertical" value="5" literal="center_vertical"/>
    <eLiterals name="center_horizontal" value="6" literal="center_horizontal"/>
    <eLiterals name="fill" value="7" literal="fill"/>
    <eLiterals name="fill_vertical" value="8" literal="fill_vertical"/>
    <eLiterals name="fill_horizontal" value="9" literal="fill_horizontal"/>
    <eLiterals name="clip_vertical" value="10" literal="clip_vertical"/>
    <eLiterals name="clip_horizontal" value="11" literal="clip_horizontal"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FastLayoutDimensionKind">
    <eLiterals name="FILL" literal="fill"/>
    <eLiterals name="WRAP" value="1" literal="wrap"/>
    <eLiterals name="FILL_WRAP" value="2" literal="fill&amp;wrap"/>
    <eLiterals name="WRAP_FILL" value="3" literal="wrap&amp;fill"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroResModelRoot" eSuperTypes="#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resources" upperBound="-1"
        eType="#//Resource" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PropertyValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="AnyDrawablePropertyValue" eSuperTypes="#//PropertyValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="StringPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorPropertyValue" eSuperTypes="#//AnyDrawablePropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LayoutDimensionPropertyValue" eSuperTypes="#//PropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constValue" eType="#//LayoutDimensionKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LayoutDimensionKind">
    <eLiterals name="FILL" literal="fill"/>
    <eLiterals name="WRAP" value="1" literal="wrap"/>
    <eLiterals name="MATCH" value="2" literal="match"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionPropertyValue" eSuperTypes="#//PropertyValue #//LayoutDimensionPropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//DimensionValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawableResourceLink" eSuperTypes="#//AnyDrawablePropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//DrawableResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabDrawableResourceLink">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//TabDrawableResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalDrawableResourceLink" eSuperTypes="#//AnyDrawablePropertyValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalResource" eType="#//AndroidDrawableResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AndroidDrawableResource">
    <eLiterals name="edit_text" literal="edit_text"/>
    <eLiterals name="editbox_background" value="1" literal="editbox_background"/>
    <eLiterals name="editbox_background_normal" value="2" literal="editbox_background_normal"/>
    <eLiterals name="editbox_dropdown_dark_frame" value="3" literal="editbox_dropdown_dark_frame"/>
    <eLiterals name="editbox_dropdown_light_frame" value="4" literal="editbox_dropdown_light_frame"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringResourceLink" eSuperTypes="#//StringPropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//StringResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerResourceLink" eSuperTypes="#//IntegerPropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//IntegerResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanResourceLink" eSuperTypes="#//BooleanPropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//BooleanResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorResourceLink" eSuperTypes="#//ColorPropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//ColorResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionResourceLink" eSuperTypes="#//DimensionPropertyValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="link" eType="#//DimensionResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="#//DimensionValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayResource" eSuperTypes="#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerArrayResource" eSuperTypes="#//ArrayResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//IntegerArrayEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerArrayEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringArrayResource" eSuperTypes="#//ArrayResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entries" upperBound="-1"
        eType="#//StringArrayEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringArrayEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawableResource" eSuperTypes="#//Resource"/>
  <eClassifiers xsi:type="ecore:EClass" name="BitmapDrawableResource" eSuperTypes="#//DrawableResource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filename" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransitionDrawableResource" eSuperTypes="#//DrawableResource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//BitmapDrawableResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//BitmapDrawableResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TabDrawableResource" eSuperTypes="#//Resource">
    <eStructuralFeatures xsi:type="ecore:EReference" name="selected" eType="#//BitmapDrawableResource"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="unselected" eType="#//BitmapDrawableResource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DimensionValue">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="metric" eType="#//DimensionMetric"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DimensionMetric">
    <eLiterals name="dp" literal="dp"/>
    <eLiterals name="sp" value="1" literal="sp"/>
    <eLiterals name="pt" value="2" literal="pt"/>
    <eLiterals name="px" value="3" literal="px"/>
    <eLiterals name="mm" value="4" literal="mm"/>
    <eLiterals name="in" value="5" literal="in"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BaseGameActivity" eSuperTypes="#//Activity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//Size" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="#//ScreenOrientation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scene" eType="#//Scene"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroGameRoot" eSuperTypes="#//ModelRoot">
    <eStructuralFeatures xsi:type="ecore:EReference" name="androGameComponents" upperBound="-1"
        eType="#//AndroGameComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroGameComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroGameGui" eSuperTypes="#//AndroGameComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gameElements" upperBound="-1"
        eType="#//GameComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndroGameLogic" eSuperTypes="#//AndroGameComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="box2dOptions" eType="#//Box2DOptions"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicComponent" upperBound="-1"
        eType="#//LogicComponent" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Box2DOptions">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gravity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Joint" eSuperTypes="#//LogicComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="first" eType="#//Body"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="second" eType="#//Body"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RevoluteJoint" eSuperTypes="#//Joint"/>
  <eClassifiers xsi:type="ecore:EClass" name="DistanceJoint" eSuperTypes="#//Joint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Body" eSuperTypes="#//Bindable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bodyType" eType="#//BodyType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="fixture" eType="#//Fixture"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineBody" eSuperTypes="#//Body"/>
  <eClassifiers xsi:type="ecore:EClass" name="CircleBody" eSuperTypes="#//Body"/>
  <eClassifiers xsi:type="ecore:EClass" name="BoxBody" eSuperTypes="#//Body"/>
  <eClassifiers xsi:type="ecore:EClass" name="Fixture" eSuperTypes="#//LogicComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="density" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="friction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="restitution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BodyType">
    <eLiterals name="static" literal="static"/>
    <eLiterals name="kinetic" value="1" literal="kinetic"/>
    <eLiterals name="dynamic" value="2" literal="dynamic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Binding" eSuperTypes="#//LogicComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindable" eType="#//Bindable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bindingTarget" eType="#//BindingTarget"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bindable" eSuperTypes="#//LogicComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scene" eSuperTypes="#//GameComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="gameBackground" eType="#//GameBackground"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="entities" upperBound="-1"
        eType="#//GameEntity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MenuScene" eSuperTypes="#//Scene">
    <eStructuralFeatures xsi:type="ecore:EReference" name="menuItems" upperBound="-1"
        eType="#//GameMenuItem" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameBackground">
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textureRegion" eType="#//TextureRegion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameMenuItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="font" eType="#//Font"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textureRegion" eType="#//TextureRegion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleEntity" eSuperTypes="#//GameEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Position"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//Size" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//GameEntity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BindingTarget"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntityBindingTarget" eSuperTypes="#//BindingTarget">
    <eStructuralFeatures xsi:type="ecore:EReference" name="entity" eType="#//GameEntity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityModifier" eSuperTypes="#//Bindable"/>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceEntityModifier" eSuperTypes="#//EntityModifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" unique="false"
        upperBound="-1" eType="#//EntityModifier"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LoopEntityModifier" eSuperTypes="#//EntityModifier">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifiers" unique="false"
        upperBound="-1" eType="#//EntityModifier"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveModifier" eSuperTypes="#//EntityModifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//FromDouble"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//ToDouble"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MoveByModifier" eSuperTypes="#//EntityModifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="by" eType="#//ByDouble"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ScaleModifier" eSuperTypes="#//EntityModifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//FromSingle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//ToSingle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlphaModifier" eSuperTypes="#//EntityModifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//FromSingle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//ToSingle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RotationByModifier" eSuperTypes="#//EntityModifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="by" eType="#//BySingle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RotationModifier" eSuperTypes="#//EntityModifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//FromSingle"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//ToSingle"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ColorModifier" eSuperTypes="#//EntityModifier">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//FromTriple"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//ToTriple"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToTriple">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="first" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="second" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="third" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FromTriple">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="first" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="second" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="third" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToDouble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FromDouble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ToSingle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FromSingle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ByDouble">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BySingle">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Line" eSuperTypes="#//GameEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="from" eType="#//FromDouble"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="to" eType="#//ToDouble"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineWidth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//GameEntity">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Position"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="font" eType="#//Font"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="halign" eType="#//HorizontalAlign"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Rectangle" eSuperTypes="#//GameEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Position"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//Size" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sprite" eSuperTypes="#//GameEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Position"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//Size" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textureRegion" eType="#//TextureRegion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AnimatedSprite" eSuperTypes="#//GameEntity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="position" eType="#//Position"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="size" eType="#//Size" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textureRegion" eType="#//TextureRegion"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="animate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Color">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="r" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="g" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="b" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="a" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constantColor" eType="#//ConstantColor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Position">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Size">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="w" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="h" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextureRegion" eSuperTypes="#//GameComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fileName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tiled" eType="#//Tiled"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Tiled">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="column" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Font" eSuperTypes="#//GameComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//FontType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="color" eType="#//Color"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="antialias" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstantColor">
    <eLiterals name="BLACK" literal="BLACK"/>
    <eLiterals name="WHITE" value="1" literal="WHITE"/>
    <eLiterals name="RED" value="2" literal="RED"/>
    <eLiterals name="GREEN" value="3" literal="GREEN"/>
    <eLiterals name="BLUE" value="4" literal="BLUE"/>
    <eLiterals name="YELLOW" value="5" literal="YELLOW"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="HorizontalAlign">
    <eLiterals name="LEFT" literal="LEFT"/>
    <eLiterals name="RIGHT" value="1" literal="RIGHT"/>
    <eLiterals name="CENTER" value="2" literal="CENTER"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FontType">
    <eLiterals name="BOLD" literal="BOLD"/>
    <eLiterals name="ITALIC" value="1" literal="ITALIC"/>
    <eLiterals name="BOLD_ITALIC" value="2" literal="BOLD_ITALIC"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScreenOrientation">
    <eLiterals name="landscape" literal="landscape"/>
    <eLiterals name="portrait" value="1" literal="portrait"/>
  </eClassifiers>
</ecore:EPackage>
