/*******************************************************************************
 * EMF Specific API of the androtext.applicationMainActivityIsTabActivity pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package patternmatchers.androtext;

import java.util.Collection;

import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.exception.IncQueryRuntimeException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.ReteEngine;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;

import signatures.androtext.ApplicationMainActivityIsTabActivitySignature;

/**
 * Generated domain-specific pattern matcher API of of the androtext.applicationMainActivityIsTabActivity pattern.
 * Please instantiate using the static field FACTORY.
 */
@SuppressWarnings("unused")
public class ApplicationMainActivityIsTabActivityMatcher extends BaseGeneratedMatcher<ApplicationMainActivityIsTabActivitySignature> implements IncQueryMatcher<ApplicationMainActivityIsTabActivitySignature>{

	public final static IMatcherFactory<ApplicationMainActivityIsTabActivitySignature,ApplicationMainActivityIsTabActivityMatcher> FACTORY = new Factory();
	public static class Factory extends BaseMatcherFactory<ApplicationMainActivityIsTabActivitySignature,ApplicationMainActivityIsTabActivityMatcher> {
			@Override
			public ApplicationMainActivityIsTabActivityMatcher instantiate(ReteEngine<String> reteEngine) throws IncQueryRuntimeException {
				return new ApplicationMainActivityIsTabActivityMatcher(reteEngine);
			}
			@Override
			public String getPatternName() {
				return "androtext.applicationMainActivityIsTabActivity";
			}
		} 
			
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param Application the fixed value of pattern parameter Application, or null if not bound.
	 * @param Activity the fixed value of pattern parameter Activity, or null if not bound.
	 * @return matches represented as an array containing the values of each parameter.
	 */
	public Collection<Object[]> getAllMatchesAsArray(Object Application, Object Activity) {
		return getAllMatchesAsArray(new Object[] {Application, Activity});
	}
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param Application the fixed value of pattern parameter Application, or null if not bound.
	 * @param Activity the fixed value of pattern parameter Activity, or null if not bound.
	 * @return matches represented as a ApplicationMainActivityIsTabActivitySignature object.
	 */
	public Collection<ApplicationMainActivityIsTabActivitySignature> getAllMatchesAsSignature(Object Application, Object Activity) {
		return getAllMatchesAsSignature(new Object[] {Application, Activity});
	}

	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param Application the fixed value of pattern parameter Application, or null if not bound.
	 * @param Activity the fixed value of pattern parameter Activity, or null if not bound.
	 * @return a match represented as an array containing the values of each parameter, or null if no match is found.
	 */
	public Object[] getOneMatchAsArray(Object Application, Object Activity) {
		return getOneMatchAsArray(new Object[] {Application, Activity});
	}
	
	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param Application the fixed value of pattern parameter Application, or null if not bound.
	 * @param Activity the fixed value of pattern parameter Activity, or null if not bound.
	 * @return a match represented as a ApplicationMainActivityIsTabActivitySignature object, or null if no match is found.
	 */
	public ApplicationMainActivityIsTabActivitySignature getOneMatchAsSignature(Object Application, Object Activity) {
		return getOneMatchAsSignature(new Object[] {Application, Activity});
	}
	
	/**
	 * Indicates whether the given combination of specified pattern parameters constitute a valid pattern match,
	 * 	under any possible substitution of the unspecified parameters.
	 * @param Application the fixed value of pattern parameter Application, or null if not bound.
	 * @param Activity the fixed value of pattern parameter Activity, or null if not bound.
	 * @return true if the input is a valid (partial) match of the pattern.
	 */
	public boolean hasMatch(Object Application, Object Activity) {
		return hasMatch(new Object[] {Application, Activity});
	}
	
	/** 
	 * Returns the number of all pattern matches given some fixed parameters.
	 * @param Application the fixed value of pattern parameter Application, or null if not bound.
	 * @param Activity the fixed value of pattern parameter Activity, or null if not bound.
	 * @return the number of pattern matches found.
	 */	
	public int countMatches(Object Application, Object Activity) {
		return countMatches(new Object[] {Application, Activity});
	}
	


	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getPatternName()
	 */
	@Override
	public String getPatternName() {
		return "androtext.applicationMainActivityIsTabActivity";
	}

	private static final String[] paramNames = new String[] {"Application", "Activity"};
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getParameterNames()
	 */
	@Override
	public String[] getParameterNames() {
		return paramNames;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher#tupleToSignature(org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple)
	 */
	@Override
	protected ApplicationMainActivityIsTabActivitySignature tupleToSignature(Tuple t) {
		return new ApplicationMainActivityIsTabActivitySignature(t.get(0), t.get(1));
	}
	
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#arrayToSignature(java.lang.Object[])
	 */
	@Override
	public ApplicationMainActivityIsTabActivitySignature arrayToSignature(Object[] signature) {
		return new ApplicationMainActivityIsTabActivitySignature(signature[0], signature[1]);
	}	
	
	private ApplicationMainActivityIsTabActivityMatcher(ReteEngine<String> engine) throws IncQueryRuntimeException {
		super(engine, "androtext.applicationMainActivityIsTabActivity");
	}
		
}
