/*******************************************************************************
 * EMF Specific API of the androtext.entityHasName pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package patternmatchers.androtext;

import java.util.Collection;

import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IMatcherFactory;
import org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher;
import org.eclipse.viatra2.emf.incquery.runtime.exception.IncQueryRuntimeException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.ReteEngine;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;

import signatures.androtext.EntityHasNameSignature;

/**
 * Generated domain-specific pattern matcher API of of the androtext.entityHasName pattern.
 * Please instantiate using the static field FACTORY.
 */
@SuppressWarnings("unused")
public class EntityHasNameMatcher extends BaseGeneratedMatcher<EntityHasNameSignature> implements IncQueryMatcher<EntityHasNameSignature>{

	public final static IMatcherFactory<EntityHasNameSignature,EntityHasNameMatcher> FACTORY = new Factory();
	public static class Factory extends BaseMatcherFactory<EntityHasNameSignature,EntityHasNameMatcher> {
			@Override
			public EntityHasNameMatcher instantiate(ReteEngine<String> reteEngine) throws IncQueryRuntimeException {
				return new EntityHasNameMatcher(reteEngine);
			}
			@Override
			public String getPatternName() {
				return "androtext.entityHasName";
			}
		} 
			
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param Named the fixed value of pattern parameter Named, or null if not bound.
	 * @param Name the fixed value of pattern parameter Name, or null if not bound.
	 * @return matches represented as an array containing the values of each parameter.
	 */
	public Collection<Object[]> getAllMatchesAsArray(Object Named, Object Name) {
		return getAllMatchesAsArray(new Object[] {Named, Name});
	}
	
	/** 
	 * Returns the set of all pattern matches given some fixed parameters.
	 * @param Named the fixed value of pattern parameter Named, or null if not bound.
	 * @param Name the fixed value of pattern parameter Name, or null if not bound.
	 * @return matches represented as a EntityHasNameSignature object.
	 */
	public Collection<EntityHasNameSignature> getAllMatchesAsSignature(Object Named, Object Name) {
		return getAllMatchesAsSignature(new Object[] {Named, Name});
	}

	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param Named the fixed value of pattern parameter Named, or null if not bound.
	 * @param Name the fixed value of pattern parameter Name, or null if not bound.
	 * @return a match represented as an array containing the values of each parameter, or null if no match is found.
	 */
	public Object[] getOneMatchAsArray(Object Named, Object Name) {
		return getOneMatchAsArray(new Object[] {Named, Name});
	}
	
	/** 
	 * Returns an arbitrary pattern match given some fixed parameters.
	 * Neither determinism nor randomness of selection is guaranteed.
	 * @param Named the fixed value of pattern parameter Named, or null if not bound.
	 * @param Name the fixed value of pattern parameter Name, or null if not bound.
	 * @return a match represented as a EntityHasNameSignature object, or null if no match is found.
	 */
	public EntityHasNameSignature getOneMatchAsSignature(Object Named, Object Name) {
		return getOneMatchAsSignature(new Object[] {Named, Name});
	}
	
	/**
	 * Indicates whether the given combination of specified pattern parameters constitute a valid pattern match,
	 * 	under any possible substitution of the unspecified parameters.
	 * @param Named the fixed value of pattern parameter Named, or null if not bound.
	 * @param Name the fixed value of pattern parameter Name, or null if not bound.
	 * @return true if the input is a valid (partial) match of the pattern.
	 */
	public boolean hasMatch(Object Named, Object Name) {
		return hasMatch(new Object[] {Named, Name});
	}
	
	/** 
	 * Returns the number of all pattern matches given some fixed parameters.
	 * @param Named the fixed value of pattern parameter Named, or null if not bound.
	 * @param Name the fixed value of pattern parameter Name, or null if not bound.
	 * @return the number of pattern matches found.
	 */	
	public int countMatches(Object Named, Object Name) {
		return countMatches(new Object[] {Named, Name});
	}
	


	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getPatternName()
	 */
	@Override
	public String getPatternName() {
		return "androtext.entityHasName";
	}

	private static final String[] paramNames = new String[] {"Named", "Name"};
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#getParameterNames()
	 */
	@Override
	public String[] getParameterNames() {
		return paramNames;
	}

	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.impl.BaseGeneratedMatcher#tupleToSignature(org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple)
	 */
	@Override
	protected EntityHasNameSignature tupleToSignature(Tuple t) {
		return new EntityHasNameSignature(t.get(0), t.get(1));
	}
	
	/* (non-Javadoc)
	 * @see org.eclipse.viatra2.emf.incquery.runtime.api.IncQueryMatcher#arrayToSignature(java.lang.Object[])
	 */
	@Override
	public EntityHasNameSignature arrayToSignature(Object[] signature) {
		return new EntityHasNameSignature(signature[0], signature[1]);
	}	
	
	private EntityHasNameMatcher(ReteEngine<String> engine) throws IncQueryRuntimeException {
		super(engine, "androtext.entityHasName");
	}
		
}
