/*
* generated by Xtext
*/
package hu.bme.mit.androtext.lang;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class AndroTextDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return hu.bme.mit.androtext.lang.ui.internal.AndroTextDslActivator.getInstance().getInjector("hu.bme.mit.androtext.lang.AndroTextDsl");
	}
	
}
