/*******************************************************************************
 * Pattern builder for pattern androtext.entityHasName
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.androtext;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern androtext.entityHasName
 */
public class PatternBuilderForentityHasName implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("androtext.entityHasName".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("androtext.entityHasName");
		
		final Address<? extends Receiver> var_17 = buildable.patternCollector("androtext.entityHasName");
		final Stub<Address<? extends Supplier>> var_18 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_19 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://www.bme.hu/mit/androtext/lang/AndroTextDsl").getEClassifier("Entity"))).getEStructuralFeature("name");
		final Stub<Address<? extends Supplier>> var_20 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"Named", "Name"}), var_19);
		final TupleMask var_21 = new TupleMask(new int[] {}, 0);
		final TupleMask var_22 = new TupleMask(new int[] {}, 2);
		final TupleMask var_23 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_24 = buildable.buildBetaNode(var_18, var_20, var_21, var_22, var_23, false);
		final Stub<Address<? extends Supplier>> var_25 = buildable.buildInjectivityChecker(var_24, 1, new int[] {0});
		final TupleMask var_26 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_27 = buildable.buildTrimmer(var_25, var_26);
		buildable.buildConnection(var_27, var_17);
		return var_17;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("androtext.entityHasName".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("Named", 0);
			posMapping.put("Name", 1);

		}
		return posMapping;
	}
}
