/*******************************************************************************
 * Pattern builder for pattern androtext.applicationModelElementHasName
 * Generated by EMF-IncQuery
 * Should contribute a pattern-builder to extension point
 * org.eclipse.viatra2.emf.incquery.codegen.patternmatcher.builder 
 *******************************************************************************/

package patternbuilders.androtext;

import java.util.HashMap;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.viatra2.emf.incquery.runtime.IStatelessGeneratedRetePatternBuilder;
import org.eclipse.viatra2.emf.incquery.runtime.term.VPMTermEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.boundary.AbstractEvaluator;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.ReteContainerBuildable;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.RetePatternBuildException;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.construction.Stub;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.matcher.IPatternMatcherContext;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Receiver;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.network.Supplier;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.remote.Address;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.FlatTuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.Tuple;
import org.eclipse.viatra2.gtasm.patternmatcher.incremental.rete.tuple.TupleMask;

/**
 * Generated automatically from pattern androtext.applicationModelElementHasName
 */
public class PatternBuilderForapplicationModelElementHasName implements IStatelessGeneratedRetePatternBuilder {
	@Override
	public Address<? extends Receiver> construct(
			ReteContainerBuildable<String> buildable,
			IPatternMatcherContext<String> context, String gtPattern)
			throws RetePatternBuildException {
		assert("androtext.applicationModelElementHasName".equals(gtPattern));
		buildable = buildable.getNextContainer().putOnTab("androtext.applicationModelElementHasName");
		
		final Address<? extends Receiver> var_39 = buildable.patternCollector("androtext.applicationModelElementHasName");
		final Stub<Address<? extends Supplier>> var_40 = buildable.buildStartStub(new Object[] {}, new Object[] {});
		final Object var_41 = ((EClass) (EPackage.Registry.INSTANCE.getEPackage("http://www.bme.hu/mit/androtext/lang/AndroTextDsl").getEClassifier("AndroidApplicationModelElement"))).getEStructuralFeature("name");
		final Stub<Address<? extends Supplier>> var_42 = buildable.binaryEdgeTypeStub(new FlatTuple(new Object[] {"Named", "Name"}), var_41);
		final TupleMask var_43 = new TupleMask(new int[] {}, 0);
		final TupleMask var_44 = new TupleMask(new int[] {}, 2);
		final TupleMask var_45 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_46 = buildable.buildBetaNode(var_40, var_42, var_43, var_44, var_45, false);
		final Stub<Address<? extends Supplier>> var_47 = buildable.buildInjectivityChecker(var_46, 1, new int[] {0});
		final TupleMask var_48 = new TupleMask(new int[] {0, 1}, 2);
		final Stub<Address<? extends Supplier>> var_49 = buildable.buildTrimmer(var_47, var_48);
		buildable.buildConnection(var_49, var_39);
		return var_39;

	}
	
	HashMap<Object, Integer> posMapping;
	@Override
	public HashMap<Object, Integer> getPosMapping(String gtPattern) {
		assert("androtext.applicationModelElementHasName".equals(gtPattern));
		if (posMapping == null) {
			posMapping = new HashMap<Object, Integer>();
			
			posMapping.put("Named", 0);
			posMapping.put("Name", 1);

		}
		return posMapping;
	}
}
