/*******************************************************************************
 * Pattern signature of the androtext.applicationModelElementHasName pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package signatures.androtext;

import java.util.Arrays;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BasePatternSignature;

/**
 * Pattern-specific signature object of the androtext.applicationModelElementHasName pattern.
 * Class fields correspond to parameters of the pattern. Fields with value null are considered unassigned.
 * Each instance is a (possibly partial) substitution of pattern parameters, 
 * usable e.g. to represent a match of the pattern in the result of a query, 
 * or to specify the bound (fixed) input parameters when issuing a query.
 */
@SuppressWarnings("unused")
public final class ApplicationModelElementHasNameSignature extends BasePatternSignature implements IPatternSignature {

	// constructor
	public ApplicationModelElementHasNameSignature(Object Named, Object Name) {
		this.fNamed = Named;
		this.fName = Name;	
	}

	//private attributes
	private Object fNamed;
	private Object fName;
	
	// getter methods
	/** Returns the value of the parameter with the given name, or null if name is invalid. */
	@Override
	public Object get(String parameterName) {
		if ("Named".equals(parameterName)) return fNamed;
		if ("Name".equals(parameterName)) return fName;
		return null;
	}	
	
	public Object getValueOfNamed(){
		 return fNamed;
	}
	public Object getValueOfName(){
		 return fName;
	}	
	
	// setter methods
	/** 
	 * Sets the parameter with the given name to the given value. 
	 * @returns true if successful, false if parameter name is invalid. May also fail and return false if the value type is incompatible. 
	 */
	@Override
	public boolean set(String parameterName, Object newValue) {
		if ("Named".equals(parameterName)) {
			fNamed = newValue;
			return true;
		}
		if ("Name".equals(parameterName)) {
			fName = newValue;
			return true;
		}
		return false;
	}
	
	public void setValueOfNamed(Object Named){
		 this.fNamed=Named;
	}
	public void setValueOfName(Object Name){
		 this.fName=Name;
	}

	// overridden prettyPrint(), hashCode(), equals() with Tuple-semantics
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (! (obj instanceof IPatternSignature))
			return false;
		IPatternSignature otherSig = (IPatternSignature) obj;
		if (!patternName().equals(otherSig.patternName()))
			return false;
		if (!ApplicationModelElementHasNameSignature.class.equals(obj.getClass()))
			return Arrays.deepEquals(toArray(), otherSig.toArray());
		ApplicationModelElementHasNameSignature other = (ApplicationModelElementHasNameSignature) obj;
		if (fNamed == null) {if (other.fNamed != null) return false;}
		else if (!fNamed.equals(other.fNamed)) return false;
		if (fName == null) {if (other.fName != null) return false;}
		else if (!fName.equals(other.fName)) return false;
		return true;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fNamed == null) ? 0 : fNamed.hashCode());
		result = prime * result + ((fName == null) ? 0 : fName.hashCode());
		return result;
	}

	@Override
	public String prettyPrint() {
		StringBuilder result = new StringBuilder();
		result.append("\"Named\"=" + prettyPrintValue(fNamed));
		result.append(", \"Name\"=" + prettyPrintValue(fName));
		return result.toString();
	}

	// conversion and reflection
	/** Converts the signature to an array representation, with each pattern parameter at their respective position */
	@Override
	public Object[] toArray() {
		return new Object[] {fNamed, fName};
	}
	
	/** Identifies the name of the pattern for which this is a signature. */
	@Override
	public String patternName() {
		return "androtext.applicationModelElementHasName";
	}
	
	/** Returns the list of symbolic parameter names. */
	@Override
	public String[] parameterNames() {
		return parameterNames;
	}
	private static String[] parameterNames = {"Named", "Name"};
	
	
}
