/*******************************************************************************
 * Pattern signature of the androtext.applicationMainActivityIsTabActivity pattern
 * Generated by EMF-IncQuery
 *******************************************************************************/

package signatures.androtext;

import java.util.Arrays;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EStructuralFeature;
import org.eclipse.viatra2.emf.incquery.runtime.api.IPatternSignature;
import org.eclipse.viatra2.emf.incquery.runtime.api.impl.BasePatternSignature;

/**
 * Pattern-specific signature object of the androtext.applicationMainActivityIsTabActivity pattern.
 * Class fields correspond to parameters of the pattern. Fields with value null are considered unassigned.
 * Each instance is a (possibly partial) substitution of pattern parameters, 
 * usable e.g. to represent a match of the pattern in the result of a query, 
 * or to specify the bound (fixed) input parameters when issuing a query.
 */
@SuppressWarnings("unused")
public final class ApplicationMainActivityIsTabActivitySignature extends BasePatternSignature implements IPatternSignature {

	// constructor
	public ApplicationMainActivityIsTabActivitySignature(Object Application, Object Activity) {
		this.fApplication = Application;
		this.fActivity = Activity;	
	}

	//private attributes
	private Object fApplication;
	private Object fActivity;
	
	// getter methods
	/** Returns the value of the parameter with the given name, or null if name is invalid. */
	@Override
	public Object get(String parameterName) {
		if ("Application".equals(parameterName)) return fApplication;
		if ("Activity".equals(parameterName)) return fActivity;
		return null;
	}	
	
	public Object getValueOfApplication(){
		 return fApplication;
	}
	public Object getValueOfActivity(){
		 return fActivity;
	}	
	
	// setter methods
	/** 
	 * Sets the parameter with the given name to the given value. 
	 * @returns true if successful, false if parameter name is invalid. May also fail and return false if the value type is incompatible. 
	 */
	@Override
	public boolean set(String parameterName, Object newValue) {
		if ("Application".equals(parameterName)) {
			fApplication = newValue;
			return true;
		}
		if ("Activity".equals(parameterName)) {
			fActivity = newValue;
			return true;
		}
		return false;
	}
	
	public void setValueOfApplication(Object Application){
		 this.fApplication=Application;
	}
	public void setValueOfActivity(Object Activity){
		 this.fActivity=Activity;
	}

	// overridden prettyPrint(), hashCode(), equals() with Tuple-semantics
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (! (obj instanceof IPatternSignature))
			return false;
		IPatternSignature otherSig = (IPatternSignature) obj;
		if (!patternName().equals(otherSig.patternName()))
			return false;
		if (!ApplicationMainActivityIsTabActivitySignature.class.equals(obj.getClass()))
			return Arrays.deepEquals(toArray(), otherSig.toArray());
		ApplicationMainActivityIsTabActivitySignature other = (ApplicationMainActivityIsTabActivitySignature) obj;
		if (fApplication == null) {if (other.fApplication != null) return false;}
		else if (!fApplication.equals(other.fApplication)) return false;
		if (fActivity == null) {if (other.fActivity != null) return false;}
		else if (!fActivity.equals(other.fActivity)) return false;
		return true;
	}
	
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((fApplication == null) ? 0 : fApplication.hashCode());
		result = prime * result + ((fActivity == null) ? 0 : fActivity.hashCode());
		return result;
	}

	@Override
	public String prettyPrint() {
		StringBuilder result = new StringBuilder();
		result.append("\"Application\"=" + prettyPrintValue(fApplication));
		result.append(", \"Activity\"=" + prettyPrintValue(fActivity));
		return result.toString();
	}

	// conversion and reflection
	/** Converts the signature to an array representation, with each pattern parameter at their respective position */
	@Override
	public Object[] toArray() {
		return new Object[] {fApplication, fActivity};
	}
	
	/** Identifies the name of the pattern for which this is a signature. */
	@Override
	public String patternName() {
		return "androtext.applicationMainActivityIsTabActivity";
	}
	
	/** Returns the list of symbolic parameter names. */
	@Override
	public String[] parameterNames() {
		return parameterNames;
	}
	private static String[] parameterNames = {"Application", "Activity"};
	
	
}
